--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-18 10:14:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5299 (class 0 OID 0)
-- Dependencies: 7
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 21498)
-- Name: cyclingactivity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cyclingactivity (
    cadencia double precision,
    kilo_julios double precision,
    potenciometro boolean,
    vatios_maximos double precision,
    vatios_medios double precision,
    id bigint NOT NULL
);


ALTER TABLE public.cyclingactivity OWNER TO sportuser;

--
-- TOC entry 224 (class 1259 OID 16947)
-- Name: document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document (
    id integer NOT NULL,
    file_path character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    size bigint,
    type character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.document OWNER TO sportuser;

--
-- TOC entry 223 (class 1259 OID 16946)
-- Name: document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16954)
-- Name: document_vector_store; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document_vector_store (
    document_id integer NOT NULL,
    vector_store_id character varying(255) NOT NULL,
    chunk_index integer
);


ALTER TABLE public.document_vector_store OWNER TO sportuser;

--
-- TOC entry 221 (class 1259 OID 16399)
-- Name: metricasalud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metricasalud (
    id uuid NOT NULL,
    id_usuario uuid NOT NULL,
    fecha_registro date NOT NULL,
    "calidad_sueño" character varying(255),
    hrv_rmssd double precision,
    hrv_sdnn double precision,
    cardiaca_reposo integer,
    descanso_subjetivo integer,
    estres_subjetivo integer,
    incidencias text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estres_medido integer,
    horas_sueno_hours integer,
    horas_sueno_minutes integer,
    peso double precision
);


ALTER TABLE public.metricasalud OWNER TO sportuser;

--
-- TOC entry 227 (class 1259 OID 21503)
-- Name: trainingactivity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainingactivity (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    desnivel double precision,
    distancia double precision,
    fecha_comienzo timestamp(6) without time zone,
    feedback text,
    hidratos double precision,
    litros_agua double precision,
    lluvia boolean,
    max_altitud double precision,
    min_altitud double precision,
    nombre character varying(255) NOT NULL,
    rpe_objetivo character varying(255),
    rpe_real character varying(255),
    temperatura double precision,
    tiempo_activo integer,
    tiempo_total integer,
    tipo character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    velocidad_maxima double precision,
    velocidad_media double precision,
    viento double precision,
    id_usuario uuid NOT NULL,
    pulso_maximo double precision,
    pulso_medio double precision,
    kilo_julios double precision,
    start_latlng double precision,
    humedad double precision,
    CONSTRAINT trainingactivity_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['CICLISMO'::character varying, 'RUNNING'::character varying, 'TRAILRUNNING'::character varying, 'FUERZA'::character varying, 'MOVILIDAD'::character varying, 'SENDERISMO'::character varying])::text[])))
);


ALTER TABLE public.trainingactivity OWNER TO sportuser;

--
-- TOC entry 220 (class 1259 OID 16388)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    nombre character varying(100),
    apellidos character varying(100),
    fecha_nacimiento timestamp(6) without time zone,
    genero character varying(10),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    strava_athlete_id bigint,
    strava_access_token character varying(512),
    strava_refresh_token character varying(512),
    strava_token_expires_at bigint
);


ALTER TABLE public.users OWNER TO sportuser;

--
-- TOC entry 222 (class 1259 OID 16937)
-- Name: vector_store; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vector_store (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    content text,
    metadata json,
    embedding public.vector(1024)
);


ALTER TABLE public.vector_store OWNER TO sportuser;

--
-- TOC entry 228 (class 1259 OID 21511)
-- Name: vuelta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vuelta (
    id bigint NOT NULL,
    desnivel integer,
    distancia double precision,
    fecha_comienzo timestamp(6) without time zone,
    pulso_maximo integer,
    pulso_medio integer,
    pulso_minimo integer,
    tiempo_activo integer,
    velocidad_media double precision,
    id_training_activity bigint NOT NULL,
    numero_vuelta integer
);


ALTER TABLE public.vuelta OWNER TO sportuser;

--
-- TOC entry 5139 (class 2606 OID 21502)
-- Name: cyclingactivity cyclingactivity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cyclingactivity
    ADD CONSTRAINT cyclingactivity_pkey PRIMARY KEY (id);


--
-- TOC entry 5135 (class 2606 OID 16953)
-- Name: document document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);


--
-- TOC entry 5137 (class 2606 OID 16958)
-- Name: document_vector_store document_vector_store_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_vector_store
    ADD CONSTRAINT document_vector_store_pkey PRIMARY KEY (document_id, vector_store_id);


--
-- TOC entry 5128 (class 2606 OID 16407)
-- Name: metricasalud metricasalud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metricasalud
    ADD CONSTRAINT metricasalud_pkey PRIMARY KEY (id);


--
-- TOC entry 5141 (class 2606 OID 21510)
-- Name: trainingactivity trainingactivity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainingactivity
    ADD CONSTRAINT trainingactivity_pkey PRIMARY KEY (id);


--
-- TOC entry 5130 (class 2606 OID 16448)
-- Name: metricasalud ukf73x8d22c7ifo0ygamgp0r1kb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metricasalud
    ADD CONSTRAINT ukf73x8d22c7ifo0ygamgp0r1kb UNIQUE (id_usuario, fecha_registro);


--
-- TOC entry 5122 (class 2606 OID 21563)
-- Name: users ukrkdhpbgw0i1q0u0f2t5wtrq5j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukrkdhpbgw0i1q0u0f2t5wtrq5j UNIQUE (strava_athlete_id);


--
-- TOC entry 5124 (class 2606 OID 16398)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 5126 (class 2606 OID 16396)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 5133 (class 2606 OID 16944)
-- Name: vector_store vector_store_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_pkey PRIMARY KEY (id);


--
-- TOC entry 5143 (class 2606 OID 21515)
-- Name: vuelta vuelta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vuelta
    ADD CONSTRAINT vuelta_pkey PRIMARY KEY (id);


--
-- TOC entry 5131 (class 1259 OID 16945)
-- Name: vector_store_embedding_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX vector_store_embedding_idx ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);


--
-- TOC entry 5145 (class 2606 OID 16959)
-- Name: document_vector_store fkbkr47oxhmwuk4o2h7odbws5ab; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_vector_store
    ADD CONSTRAINT fkbkr47oxhmwuk4o2h7odbws5ab FOREIGN KEY (document_id) REFERENCES public.document(id);


--
-- TOC entry 5148 (class 2606 OID 21526)
-- Name: vuelta fkiqfl8yuo7010c8mmnhh0c4wp5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vuelta
    ADD CONSTRAINT fkiqfl8yuo7010c8mmnhh0c4wp5 FOREIGN KEY (id_training_activity) REFERENCES public.trainingactivity(id);


--
-- TOC entry 5146 (class 2606 OID 21516)
-- Name: cyclingactivity fknr4sytnviwf2g4bnqulft2abi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cyclingactivity
    ADD CONSTRAINT fknr4sytnviwf2g4bnqulft2abi FOREIGN KEY (id) REFERENCES public.trainingactivity(id);


--
-- TOC entry 5147 (class 2606 OID 21521)
-- Name: trainingactivity fksvu6sm9knoink132uuam8pj08; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainingactivity
    ADD CONSTRAINT fksvu6sm9knoink132uuam8pj08 FOREIGN KEY (id_usuario) REFERENCES public.users(id);


--
-- TOC entry 5144 (class 2606 OID 16408)
-- Name: metricasalud metricasalud_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metricasalud
    ADD CONSTRAINT metricasalud_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.users(id);


-- Completed on 2025-08-18 10:14:47

--
-- PostgreSQL database dump complete
--

